### PR TITLE
Ubiquity 2.5.2

### PR DESCRIPTION
**Pull request by joanhey**
In reality it's using this version, in the last run.

https://github.com/myaaghubi/PHP-Frameworks-Bench/actions/runs/7091046459/job/19299321908?pr=48#step:6:2152

The `ubiquity-project` always use any version `^2.3`.
https://github.com/phpMv/ubiquity-project/blob/master/composer.json#L13

### CODE REVIEW

**Comment by myaaghubi** [comment]
`1.0.9` is the same `dev-master / 2.4.x-dev`

**Comment by joanhey** [comment]
Yes, it's the same, but install always the last ubiquity version. Now it is v2.5.2.

The only thing that look that work like 2.4.x-dev, is the branch alias.
https://github.com/phpMv/ubiquity-project/blob/master/composer.json#L29-L30

**Comment by myaaghubi** [comment]
Then make sure to update it with the correct version number, sometimes the version number of the skeleton does not match the version number of the core, so it is better to consider the version number of the repository that we're going with

**Comment by joanhey** [comment]
I think that you don't understand it.

The skeleton is updated to the last `1.0.9,` that update automatically to any core v `^2.3`.
`dev-master / 2.4.x-dev` is only a branch alias, nothing else.
`^2.3` = ( >=2.3.0 <3.0.0)

The same happen with others frameworks.
For example, Cakephp app skeleton is v5.0.1, but install Cakephp core v5.0.3 and update automatically to
`"cakephp/cakephp": "^5.0.1"`.
"^5.0.1" =  ( >=5.0.1 <6.0.0=)

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by joanhey** [comment]
image

**Comment by myaaghubi** [comment]
> Then make sure to update it with the correct version number, sometimes the version number of the skeleton does not match the version number of the core, so it is better to consider the version number of the repository that we're going with

> App skeleton version don't necessary correlate to core versions.

Yep
My point is if you go with a skeleton (`create-project phpmv/ubiquity-project:1.0.*` as your commit) then you would put the version number that belongs to that skeleton, or if you go with a core and make your own skeleton for it then you would put the version number that belongs to that core
So in case, it is going to be `:1.0` (consider other frameworks that we have in the list) however you may find it far from the core version number of the `ubiquity` like myself

**Comment by joanhey** [comment]
Do it like you want it !!

**Comment by myaaghubi** [comment]
> Do it like you want it !!


Then, I prefer to keep it like before until the next update of ubiquity

**Comment by joanhey** [comment]
Perfect, but remember that now we are testing Ubiquity 25.2.
And later any new version of ubiquity automatically.

**Pull request closed without merging**
