### PR TITLE
Symfony update to  v6.3

### PR DESCRIPTION
**Pull request by joanhey**

### CODE REVIEW

**Comment by myaaghubi** [comment]
Didn't check it yet, however, guessing just the version number changed (on the folder name and in the `setup.sh`)
for this kind things we may use `git mv oldfolder newfolder`

**Comment by joanhey** [comment]
Yes I created the branch from the dev, and later send PR to main 🤭

**Comment by joanhey** [comment]
It's rare that worked without the change in the `benchmark.config`.

**Comment by myaaghubi** [comment]
I checked it are you sure it is passing `check.sh` ?

**Comment by joanhey** [comment]
Now any change that break, will not pass the GH action check.

**Comment by myaaghubi** [comment]
then it is a glitch on my machine, ok I'll make sure later

**Comment by joanhey** [comment]
mmmm I'll check again

**Pull request merged**
