### PR TITLE
Update Slim to v4.13

### PR DESCRIPTION
**Pull request by joanhey**

### CODE REVIEW

**Comment by myaaghubi** [comment]
Thanks for the PR. 
Please consider, there gonna be no update on benchmarks until the next update of PHP -8.4- (scheduled for about 7 months later, or more), and for that, frameworks gonna be needed to update again!

**Comment by joanhey** [comment]
All the frameworks update the first quarter of the year, after the new PHP version.
A good example is Laravel !!

**Comment by myaaghubi** [comment]
A fresh update for all (as possible) is necessary after the new version of PHP. Not sure I'll be able to make a mid-year update for benchmarks, so don't push yourself dude.
The PR is accepted by the way.

**Comment by joanhey** [comment]
See you next year!!! bye

**Pull request merged**
