### PR TITLE
Add apache dockerfile

### PR DESCRIPTION
**Pull request by joanhey**
I don't use apache for a lot of years ago.
And I don't want to install it only for the bench and less in port 80, and perhaps more people have the same situation.

**Advantages of use Docker:**
- We don't need apache installed in our computer
- Not necessary to copy, chown or change apache config
- Use default php:8.2-apache
- We can change to any PHP version easily in the dockerfile
- Don't pollute the hard disk with logs
- Instant display of errors and logs (easier for developers)
- It's optional, you can use your apache instead

First I needed to fix the permissions nightmare, thanks to the docker.
Still I didn't run any benchmark :(, only `check.sh`. Perhaps tonight I will run this benchmark :smile: .

PD: it's in dir `.docker` because I have another with nginx.

Work in progress!

### CODE REVIEW

**Comment by joanhey** [comment]
This morning I ran this benchmark locally, the first time.
image

**Comment by myaaghubi** [comment]
Is it still in progress?
It is helpful to share some information about your benchmarking environment besides the results.

**Comment by joanhey** [comment]
In my PC the results are very low.
It can be php official docker (not the first time that have very low performance), and I can change it to use a Ubuntu or Debian docker, and install the Apache and PHP.

**Comment by joanhey** [comment]
The Readme  say that you use Apache, but not which type of configuration: mod_php, php_fpm, mpm prefork, ....

**Comment by joanhey** [comment]
Every time I run a new benchmark overwrite the old data: local, apache docer, nginx docker, ...
It's for that I ask to add the issue #37

**Comment by myaaghubi** [comment]
By default it is prefork for Apache2, all configurations are the default for Apache & PHP
It is a simple hello world not a templated big script, however I got some timeout requests for some of the libs even with a 5-8 seconds timeout
You have a better cpu so higher scores are expected, docker is limiting, also faster libs gonna lose more scores on a hard disk so disabling CustomLog for apache2 or access_log for nginx is necessary

**Comment by joanhey** [comment]
I think that will be better to add a docker branch, and when it's well tested, we can merge in the main branch.

**Comment by joanhey** [comment]
Now you can merge it in the docker branch, so all can test it.
Later I'll send the nginx dockerfile, and it's x100 faster than the apache dockerfile.

I'll try with a new dockerfile for apache, using a Ubuntu image and installing all the required components.

**Comment by myaaghubi** [comment]
I will check it as soon as possible. For nginx consider #39 and plz make sure to add a more understandable name on `apache.sh` for users

**Pull request merged**
