### PR TITLE
Add Kumbiaphp

### PR DESCRIPTION
**Pull request by joanhey**

### CODE REVIEW

**Comment by joanhey** [comment]
I made some changes, in the bash files.

`rm -rf !("_benchmark")` don't work in bash from all OS and virtualizations.
You need to add `shopt -s globstar` first, that is not correct to have it always so.
In my debian didn't work the `clean.sh`, so I think that will happen the same to other people:
`./_benchmark/clean.sh: 2: ./_benchmark/clean.sh: Syntax error: "(" unexpected`

In `update.sh` I clean it
`composer update --no-dev --optimize-autoloader`
We can use `--no-dev --optimize-autoloader`  in `install` and `update`.
The only that don't permit `--optimize-autoloader`  is `create-project`, but still permit `--no-dev`.

**Comment by myaaghubi** [comment]
You can't use it like `./_benchmark/clean.sh` instead use `bash clean.sh -t kumbiaphp-1.1`

**Review by joanhey — COMMENTED** [review]
I removed the last `/index` to have a fair bench. I understand to add it again.

But in a benchmark the length of the response and URL is important. The response need to be exactly the same length. In this case the response is 33b, 12b from the "Hello World!" and the rest from the output data.

The top performers in this bench, don't use a public dir in the URL.
Siler, Fatfree, Slim, ... they don't have a default public dir.
So the index.php is created inside the framework dir, not inside a public dir.

URLs:
url="$base/$fw/index.php/hello/index"
url="$base/$fw/public/index.php/hello/index"
url="$base/$fw/default/public/index.php/hello/index"
... 
a part of the length of the framework name, that also the top performers is shorter than the rest.

In some cases in this bench, the length difference of the URL is the same that the response.

We need to include the `index.php`, inside a public dir for the microframeworks that don't have it, to have a better fair play.
In a real situation, the server will point directly to the public dir from any full stack framework.

**Comment by joanhey** [comment]
Added the PR #13

**Comment by joanhey** [comment]
Woow :+1: 
You published the new data with Kumbia !!!
For a lot of years, I didn't test it without OPCache, but the results are very good.

The difference with the Kenjis bench (from 1.0-dev to 1.1.5), the most important changes for the performance are:

- Now Kumbia use `.php` config files, before `.ini`, that need to load and parse in each request
- The bench use `WRK`, `ab` was not fast enough for the faster frameworks
   I created an issue about that: https://github.com/kenjis/php-framework-benchmark/issues/62

**Pull request merged**
