### PR TITLE
Add Codeigniter 3.1

### PR DESCRIPTION
**Pull request by joanhey**
CI4 is five times slower than CI3, and they need to fix this performance regression.

Also I know this bench, because one notification in the issue that I created in CI4 about that regression.

CI3 don't work with php8.2 (exist a PR that fix that, but it isn't merged yet), but anybody can try it with with other versions.
Will be very useful for the CI core developers.

The problem, is that we need to change the `parse_results()` to by pass any framework that fail in any version.

### CODE REVIEW

**Comment by joanhey** [comment]
Later I'll try to add GHactions tests.

**Comment by myaaghubi** [comment]
Not a PR but PRs, if the speed between CI3/CI4 is different then that's useful to have CI3 in the table too, however the latest results are for PHP 8.2, so official support for it is necessary. Consider the right version after PHP 8.2 get supported

**Comment by joanhey** [comment]
We can check first the PHP version, and if PHP8.2 by pass CI3 for now, till they merge the fix.

**Comment by joanhey** [comment]
When this PR https://github.com/bcit-ci/CodeIgniter/pull/6173  is merged.
We can add CI3, and check the performance regression.

**Comment by myaaghubi** [comment]
We moved to `PHP-8.3` and `CI-3.1` not support it

**Pull request closed without merging**
